CapaPresentacionAdmin/Controllers/Mantenedor/ProductoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CapaEntidades.CapaEntidades;
using CapaDatos;
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using CapaNegocio;

namespace CapaPresentacionAdmin.Controllers.Mantenedor
{
    public class ProductoesController : Controller
    {
        private readonly DbcarritoContext _context;
        private readonly Cloudinary _cloudinary;
        private readonly ProductosService _productosService;
        public ProductoesController(DbcarritoContext context, Cloudinary cloudinary, ProductosService productosService)
        {
            _context = context;
            _cloudinary = cloudinary;
            _productosService = productosService;
        }

        // GET: Productoes
        public async Task<IActionResult> Index()
        {
            var dbcarritoContext = _context.Productos.Include(p => p.categoria).Include(p => p.Marca);
            return View(await dbcarritoContext.ToListAsync());
        }

        // GET: Productoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .Include(p => p.categoria)
                .Include(p => p.Marca)
                .FirstOrDefaultAsync(m => m.IdProducto == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // GET: Productoes/Create
        public IActionResult Create()
        {
            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Descripcion");
            ViewData["IdMarca"] = new SelectList(_context.Marcas, "IdMarca", "Descripcion");
            return View();
        }

        // POST: Productoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdProducto,Nombre,Descripcion,Precio,Stock,RutaImagen,NombreImagen,Activo,FechaRegistro,IdMarca,IdCategoria")] Producto producto, IFormFile file)
        {
            try
            {
                var (respuesta, mensaje) = await _productosService.validaCamposVacios(producto);
                if (respuesta != 1)
                {
                    //Regresa a la vista con los datos del producto
                    ModelState.AddModelError(string.Empty, mensaje);
                    ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Descripcion", producto.IdCategoria);
                    ViewData["IdMarca"] = new SelectList(_context.Marcas, "IdMarca", "Descripcion", producto.IdMarca);
                    return View(producto);
                }

                // Verifica que se haya seleccionado una imagen
                if (file == null || file.Length == 0)
                {
                    ModelState.AddModelError(string.Empty, "Error al subir la imagen. (Pueda ser que no hayas seleccionado alguna)");
                    ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Descripcion", producto.IdCategoria);
                    ViewData["IdMarca"] = new SelectList(_context.Marcas, "IdMarca", "Descripcion", producto.IdMarca);
                    return View(producto);
                }

                // Validación del tipo de archivo (solo imágenes PNG, JPG y JPEG)
                var allowedExtensions = new[] { ".png", ".jpg", ".jpeg" };
                var fileExtension = Path.GetExtension(file.FileName).ToLower();
                if (!allowedExtensions.Contains(fileExtension))
                {
                    ModelState.AddModelError(string.Empty, "Solo se permiten imágenes en formato PNG, JPG o JPEG.");
                    ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Descripcion", producto.IdCategoria);
                    ViewData["IdMarca"] = new SelectList(_context.Marcas, "IdMarca", "Descripcion", producto.IdMarca);
                    return View(producto);
                }

                if (ModelState.IsValid)
                {
                    var uploadParams = new ImageUploadParams()
                    {
                        //Archivo que estamos intentando subir
                        File = new FileDescription(file.FileName, file.OpenReadStream()),

                        //Indicamos donde queremos guardar las imagenes (Es una carpeta que cree en Cloudinary)
                        AssetFolder = "ProductsImages"
                    };
                    var uploadResult = await _cloudinary.UploadAsync(uploadParams);

                    // Asignamos la URL segura y la ruta de la imagen al producto
                    producto.RutaImagen = uploadResult.SecureUrl.ToString();
                    producto.NombreImagen = file.FileName;

                    _context.Add(producto);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $"Ocurrió un error: {ex.Message}");
            }
            return View(producto);
        }

        // GET: Productoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }

            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Descripcion");
            ViewData["IdMarca"] = new SelectList(_context.Marcas, "IdMarca", "Descripcion");
            return View(producto);
        }

        // POST: Productoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdProducto,Nombre,Descripcion,Precio,Stock,RutaImagen,NombreImagen,Activo,FechaRegistro,IdMarca,IdCategoria")] Producto producto, IFormFile? file)
        {
            if (id != producto.IdProducto)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var nombreImagenExistente = await _context.Productos
                     .Where(p => p.IdProducto == id)
                     .Select(p => p.NombreImagen)  // Solo selecciona el nombre de la imagen
                     .FirstOrDefaultAsync();
                    var rutaImagenExistente = await _context.Productos
                        .Where(p => p.IdProducto == id)
                        .Select(p => p.RutaImagen)
                        .FirstOrDefaultAsync();
                    // Si ya existe un nombre de imagen, asignalo al producto
                    producto.NombreImagen = nombreImagenExistente;
                    producto.RutaImagen = rutaImagenExistente;
                    // Verifica si hay un archivo para subir
                    if (file != null && file.Length > 0)
                    {
                        var uploadParams = new ImageUploadParams()
                        {
                            File = new FileDescription(file.FileName, file.OpenReadStream()),
                            AssetFolder = "ProductsImages"
                        };
                        var uploadResult = await _cloudinary.UploadAsync(uploadParams);

                        // Guarda la URL de Cloudinary en el producto
                        producto.RutaImagen = uploadResult.SecureUrl.ToString();
                        producto.NombreImagen = file.FileName;
                        
                    }

                    // Actualiza el producto en la base de datos con la nueva URL
                    _context.Update(producto);
                    await _context.SaveChangesAsync();

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoExists(producto.IdProducto))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "IdCategoria", "Descripcion", producto.IdCategoria);
            ViewData["IdMarca"] = new SelectList(_context.Marcas, "IdMarca", "Descripcion", producto.IdMarca);

            return View(producto);
        }

        // GET: Productoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .Include(p => p.categoria)
                .Include(p => p.Marca)
                .FirstOrDefaultAsync(m => m.IdProducto == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // POST: Productoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

CapaPresentacionAdmin/Views/Productoes/Create.cshtml
@model CapaEntidades.CapaEntidades.Producto

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 style="display: flex; justify-content:center;">Crear</h1>

<h4 style="display: flex; justify-content:center;">Producto</h4>

<hr />

<div class="row" style="display: flex; justify-content:center;">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">

            <div class="form-group">
                <label>Selecciona una imagen para subir</label>
                <input type="file" name="file" class="form-control" />
            </div>
            <hr />

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stock" class="control-label"></label>
                <input asp-for="Stock" class="form-control" />
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Categoria</label>
                <select asp-for="IdCategoria" class="form-control" asp-items="ViewBag.IdCategoria"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Marca</label>
                <select asp-for="IdMarca" class="form-control" asp-items="ViewBag.IdMarca"></select>
            </div>
            <div class="form-group mt-2" style="display: flex; justify-content:center;">
                <input type="submit" value="Crear" class="btn btn-primary me-3" />
                <a class="btn btn-danger" asp-action="Index">Regresar</a>
            </div>
            
        </form>
    </div>
</div>
<br />

<br/>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="/js/loadingoverlay.min.js"></script>
<script>
    $(document).ready(function () {
        $("form").on("submit", function () {
            $.LoadingOverlay("show",
                {
                    text: "Cargando..."
                });
        });
    });
</script>

CapaPresentacionAdmin/Views/Productoes/Delete.cshtml
@model CapaEntidades.CapaEntidades.Producto

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 style="display: flex; justify-content:center;">¿Estás seguro que quieres eliminar @Html.DisplayFor(Model => Model.Descripcion)?</h3>
<div style="display: flex; flex-direction: column; align-items: center; width: 100%;">
    <h4>Marca</h4>
    <hr style="width: 100%; max-width: 600px;" />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <dl class="row" style="width: 100%; max-width: 600px;">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Stock)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Stock)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Activo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Activo)
        </dd>
        <dt class="col-sm-2">
            Categoria
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.categoria.Descripcion)
        </dd>
        <dt class="col-sm-2">
            Marca
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Marca.Descripcion)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="IdMarca" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-info" asp-action="Index">Cancelar</a>
    </form>
</div>

CapaPresentacionAdmin/Views/Productoes/Details.cshtml
@model CapaEntidades.CapaEntidades.Producto

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Producto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stock)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stock)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RutaImagen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RutaImagen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreImagen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreImagen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Activo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Activo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaRegistro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaRegistro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.categoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.categoria.IdCategoria)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca.IdMarca)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdProducto">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CapaPresentacionAdmin/Views/Productoes/Edit.cshtml
@model CapaEntidades.CapaEntidades.Producto

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar</h1>

<h4>Producto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdProducto" />
            <div class="form-group">
                <label class="control-label">Imagen Actual</label>
                <div>
                    @if (!string.IsNullOrEmpty(Model.RutaImagen))
                    {
                        <img src="@Model.RutaImagen" alt="Imagen del producto" class="img-thumbnail" width="200" />
                    }
                    else
                    {
                        <p>No hay imagen disponible</p>
                    }
                </div>
            </div>

            <div class="form-group">
                <label>Nueva Imagen</label>
                <input type="file" name="file" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stock" class="control-label"></label>
                <input asp-for="Stock" class="form-control" />
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            <label class="control-label">Activo</label>
            <div class="form-check form-switch">
                @Html.CheckBox("Activo", Model.Activo ?? false, new { @class = "form-check-input", id = "flexSwitchCheckDefault" })
                <label class="form-check-label" for="flexSwitchCheckDefault" id="switchLabel">
                    @if (Model.Activo ?? false)
                    {
                        <span class="badge bg-success">Sí</span>
                    }
                    else
                    {
                        <span class="badge bg-danger">No</span>
                    }
                </label>
                @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="control-label">Marca</label>
                <select asp-for="IdMarca" class="form-control" asp-items="ViewBag.IdMarca"></select>
                <span asp-validation-for="IdMarca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Categoria</label>
                <select asp-for="IdCategoria" class="form-control" asp-items="ViewBag.IdCategoria"></select>
                <span asp-validation-for="IdCategoria" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                <a class="btn btn-danger" asp-action="Index">Regresar</a>
            </div>
        </form>
    </div>
</div>

<script>

    var checkbox = document.getElementById('flexSwitchCheckDefault');
    var label = document.getElementById('switchLabel');


    checkbox.addEventListener('change', function () {
        var badge = label.querySelector('span');


        if (checkbox.checked) {
            badge.classList.remove('bg-danger');
            badge.classList.add('bg-success');
            badge.textContent = 'SÍ';
        } else {
            badge.classList.remove('bg-success');
            badge.classList.add('bg-danger');
            badge.textContent = 'nO';
        }
    });
</script>

CapaPresentacionAdmin/Views/Productoes/Index.cshtml
@model IEnumerable<CapaEntidades.CapaEntidades.Producto>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.5.0/css/responsive.dataTables.min.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.5.0/js/dataTables.responsive.min.js"></script>
</head>
<h1>Marcas</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Productoes")">Mantenimiento</a></li>
    <li class="breadcrumb-item active">Crear</li>
</ol>
<div class="card">
    <div class="card-header" style="background-color:#685752; color: white;">
        <i class="fas fa-list me-3"></i>Productos
    </div>
    <div class="card-body" style="background-color: #997C70; color: white;">
        
        <p>
            <a asp-action="Create" class="btn mt-1 mb-2" style="background-color:#8EB486">Nuevo Producto</a>
        </p>
        
        <table id="MarcaTable" class="table table-striped nowrap" style="width:100%; text-align: center; vertical-align: middle;">
            <thead >
                <tr style="color: #FDF7F4">
                    <th style="text-align: center; vertical-align: middle;">
                        Producto
                    </th>
                    <th style="text-align: center; vertical-align: middle;">
                        Descripción
                    </th>
                    <th style="text-align: center; vertical-align: middle;">
                        @Html.DisplayNameFor(model => model.Precio)
                    </th>
                    <th style="text-align: center; vertical-align: middle;">
                        Cantidad
                    </th>
                    <th style="text-align: center; vertical-align: middle;">
                        @Html.DisplayNameFor(model => model.Activo)
                    </th>
                    <th style="text-align: center; vertical-align: middle;">
                        @Html.DisplayNameFor(model => model.categoria)
                    </th>
                    <th>
                        Marca
                    </th>
                    <th>
                        Acciones
                    </th>
                </tr>
            </thead>
            <tbody >
                @foreach (var item in Model)
                {
                    <tr style="color: #FDF7F4">
                        <td style="color: #FDF7F4">
                            @Html.DisplayFor(modelItem => item.Nombre)
                        </td>
                        <td style="color: #FDF7F4">
                            @Html.DisplayFor(modelItem => item.Descripcion)
                        </td>
                        <td style="color: #FDF7F4">
                           $@Html.DisplayFor(modelItem => item.Precio)
                        </td>
                        <td style="color: #FDF7F4">
                            @Html.DisplayFor(modelItem => item.Stock)
                        </td>
                        <td style="color: #FDF7F4">
                            @if (item.Activo == true)
                            {
                                <span class="badge" style="background-color: #B1C29E">Sí </span>
                            }
                            else
                            {
                                <span class="badge" style="background-color: #E5989B">No </span>
                            }
                        </td>
                        <td style="color: #FDF7F4">
                            @Html.DisplayFor(modelItem => item.categoria.Descripcion)
                        </td>
                        <td style="color: #FDF7F4">
                            @Html.DisplayFor(modelItem => item.Marca.Descripcion)
                        </td>
                        <td style="color: #FDF7F4">
                            <a asp-action="Edit" class="btn" style="background-color: #FADA7A" asp-route-id="@item.IdProducto">
                                <i class="fas fa-pen-to-square"></i>
                            </a> |
                            <a asp-action="Details" class="btn" style="background-color: #98D8EF" asp-route-id="@item.IdProducto">
                                <i class="fas fa-eye"></i>
                            </a> |
                            <a asp-action="Delete" class="btn" style="background-color: #E5989B" asp-route-id="@item.IdProducto">
                                <i class="fas fa-trash-can"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#MarcaTable').DataTable({
            responsive: true,
            language: {
                url: "//cdn.datatables.net/plug-ins/1.13.6/i18n/es-MX.json"
            }
        });
    });
</script>